# GTNH buildscript settings, based on gtnh-factory-flow's gtnh-calc-oracle
# (MIT, Copyright (c) 2026 Samiracle64, jackwrichards).
gtnh.settings.blowdryerTag = 0.2.2
modName = GCM Icon Export
modId = gcmiconexport
modGroup = gcm.iconexport
useModGroupForPublishing = false
autoUpdateBuildScript = false
minecraftVersion = 1.7.10
forgeVersion = 10.13.4.1614
channel = stable
mappingsVersion = 12
remoteMappings = https\://raw.githubusercontent.com/MinecraftForge/FML/1.7.10/conf/
developmentEnvironmentUserName = GCMIconExport
enableModernJavaSyntax = jabel
enableGenericInjection = true
generateGradleTokenClass = gcm.iconexport.Tags
gradleTokenVersion = VERSION
replaceGradleTokenInFile =
apiPackage =
accessTransformersFile =
usesMixins = false
separateMixinSourceSet =
usesMixinDebug = false
mixinPlugin =
mixinsPackage =
coreModClass =
containsMixinsAndOrCoreModOnly = false
forceEnableMixins = false
usesShadowedDependencies = false
minimizeShadowedDependencies = true
relocateShadowedDependencies = true
includeWellKnownRepositories = true
excludeWellKnownRepositories =
usesMavenPublishing = false
noPublishedSources = true
disableSpotless = true
disableCheckstyle = true
org.gradle.configuration-cache = true
org.gradle.parallel = true
